services:
  app:
    build: .
    image: load:latest
    ports:
      - "${SEREVER_PORT:-8080}:${SEREVER_PORT:-8080}"
    env_file:
      - .env
    environment:
      SEREVER_PORT: ${SEREVER_PORT:-8080}
