spring.application.name=load
spring.config.import=optional:file:.env[.properties]
server.port=${SERVER_PORT}
bucket-adapter.base-url=${BUCKET_ADAPTER_BASE_URL}
server.servlet.context-path=/api

etl.mqtt.enabled=${MQTT_ENABLED:false}
etl.mqtt.broker-url=${MQTT_BROKER_URL:tcp://localhost:1883}
etl.mqtt.client-id=${MQTT_CLIENT_ID:}
etl.mqtt.namespace=${MQTT_NAMESPACE:stack1}
etl.mqtt.service-name=${MQTT_SERVICE_NAME:load}
etl.mqtt.schema-version=${MQTT_SCHEMA_VERSION:1.0}
etl.mqtt.username=${MQTT_USERNAME:}
etl.mqtt.password=${MQTT_PASSWORD:}
