package com.bucketadapter.service.sql;

import com.bucketadapter.dto.Rows.CustomerRow;
import com.bucketadapter.dto.Rows.OrderItemRow;
import com.bucketadapter.dto.Rows.OrderRow;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.stream.Collectors;

@Service
public class SqlScriptService {

    public String generate(
            List<CustomerRow> customers,
            List<OrderRow> orders,
            List<OrderItemRow> orderItems
    ) {
        StringBuilder sb = new StringBuilder(8_192);
        sb.append("-- generated by load\n");
        sb.append("START TRANSACTION;\n\n");

        sb.append(upsertCustomers(customers)).append("\n");
        sb.append(upsertOrders(orders)).append("\n");
        sb.append(upsertOrderItems(orderItems)).append("\n");

        sb.append("\nCOMMIT;\n");
        return sb.toString();
    }

    private String upsertCustomers(List<CustomerRow> rows) {
        if (rows == null || rows.isEmpty()) return "-- customers: 0 row\n";

        String values = rows.stream()
                .map(r -> "("
                        + SqlValueEncoder.v(r.customerId()) + ","
                        + SqlValueEncoder.v(r.email()) + ","
                        + SqlValueEncoder.v(r.firstName()) + ","
                        + SqlValueEncoder.v(r.lastName()) + ","
                        + SqlValueEncoder.v(r.isActive())
                        + ")")
                .collect(Collectors.joining(",\n"));

        return "INSERT INTO customers (customer_id, email, first_name, last_name, is_active)\n"
                + "VALUES\n" + values + "\n"
                + "ON DUPLICATE KEY UPDATE\n"
                + "  email=VALUES(email),\n"
                + "  first_name=VALUES(first_name),\n"
                + "  last_name=VALUES(last_name),\n"
                + "  is_active=VALUES(is_active);\n";
    }

    private String upsertOrders(List<OrderRow> rows) {
        if (rows == null || rows.isEmpty()) return "-- orders: 0 row\n";

        String values = rows.stream()
                .map(r -> "("
                        + SqlValueEncoder.v(r.orderId()) + ","
                        + SqlValueEncoder.v(r.customerId()) + ","
                        + SqlValueEncoder.v(r.status()) + ","
                        + SqlValueEncoder.v(r.total())
                        + ")")
                .collect(Collectors.joining(",\n"));

        return "INSERT INTO orders (order_id, customer_id, status, total)\n"
                + "VALUES\n" + values + "\n"
                + "ON DUPLICATE KEY UPDATE\n"
                + "  customer_id=VALUES(customer_id),\n"
                + "  status=VALUES(status),\n"
                + "  total=VALUES(total);\n";
    }

    private String upsertOrderItems(List<OrderItemRow> rows) {
        if (rows == null || rows.isEmpty()) return "-- order_items: 0 row\n";

        String values = rows.stream()
                .map(r -> "("
                        + SqlValueEncoder.v(r.orderId()) + ","
                        + SqlValueEncoder.v(r.lineNo()) + ","
                        + SqlValueEncoder.v(r.sku()) + ","
                        + SqlValueEncoder.v(r.qty()) + ","
                        + SqlValueEncoder.v(r.unitPrice())
                        + ")")
                .collect(Collectors.joining(",\n"));

        return "INSERT INTO order_items (order_id, line_no, sku, qty, unit_price)\n"
                + "VALUES\n" + values + "\n"
                + "ON DUPLICATE KEY UPDATE\n"
                + "  sku=VALUES(sku),\n"
                + "  qty=VALUES(qty),\n"
                + "  unit_price=VALUES(unit_price);\n";
    }

    public static String deriveSqlRemote(String remote) {
        if (remote == null || remote.isBlank()) return "script.sql";
        if (remote.endsWith(".json")) return remote.substring(0, remote.length() - 5) + ".sql";
        if (remote.endsWith(".sql")) return remote;
        return remote + ".sql";
    }
}

